sudo: required
services:
        - docker

before_install:
        - docker build -t luisfy/docker-react -f Dockerfile.dev .

script:
        - docker run luisfy/docker-react npm run test -- --coverage

