sudo: required
services:
        - docker

before_install:
        - docker build -t luisfy/docker-react .

script:
        - docker run luisfy/docker-react

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-195995829288"
        bucker_path": "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
